before:
  hooks:
    - go mod tidy
builds:
  - binary: local
    id: local
    main: ./cmd/local/main.go
    goos:
      - windows
      - darwin
      - linux
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
  - binary: server
    id: server
    main: ./cmd/server/main.go
    goos:
      - windows
      - darwin
      - linux
      - freebsd
    goarch:
      - amd64
      - 386
      - arm