name: release
on:
  push:
    branches: main
jobs:
  goreleaser:
    runs-on: ubuntu-latest

    #    env:
#      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Check out code into the Go module directory
          uses: actions/checkout@v1
            - name: Get dependencies
              run: go mod tidy
            - name: Test
              run: go test ./...
#      - name: Docker release
#        uses: elgohr/Publish-Docker-Github-Action@master
#        with:
#          name: gwuhaolin/lightsocks
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}